# Generated by Django 5.2 on 2026-05-07 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "xref",
                    models.CharField(
                        help_text="GEDCOM cross-reference identifier (e.g. S1)",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=512)),
                ("author", models.CharField(blank=True, max_length=512)),
                ("publisher", models.CharField(blank=True, max_length=512)),
                (
                    "publication",
                    models.TextField(blank=True, help_text="Publication facts"),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="Source text / transcription"
                    ),
                ),
                ("repository_name", models.CharField(blank=True, max_length=512)),
                (
                    "gedcom_data",
                    models.TextField(
                        blank=True, help_text="Raw GEDCOM for this record"
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="genealogy.tree",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "unique_together": {("tree", "xref")},
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full place name, comma-separated hierarchy",
                        max_length=512,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="genealogy.place",
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="genealogy.tree",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "xref",
                    models.CharField(
                        help_text="GEDCOM cross-reference identifier (e.g. N1)",
                        max_length=50,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "gedcom_data",
                    models.TextField(
                        blank=True, help_text="Raw GEDCOM for this record"
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="genealogy.tree",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "xref",
                    models.CharField(
                        help_text="GEDCOM cross-reference identifier (e.g. M1)",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=512)),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Relative path to media file",
                        max_length=1024,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "file",
                    models.FileField(blank=True, upload_to="genealogy/media/%Y/%m/"),
                ),
                (
                    "gedcom_data",
                    models.TextField(
                        blank=True, help_text="Raw GEDCOM for this record"
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="genealogy.tree",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "media",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Individual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "xref",
                    models.CharField(
                        help_text="GEDCOM cross-reference identifier (e.g. I1)",
                        max_length=50,
                    ),
                ),
                ("given_names", models.CharField(blank=True, max_length=512)),
                ("surname", models.CharField(blank=True, max_length=255)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("U", "Unknown"),
                            ("X", "Intersex"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
                (
                    "birth_date",
                    models.CharField(
                        blank=True, help_text="GEDCOM date string", max_length=100
                    ),
                ),
                (
                    "death_date",
                    models.CharField(
                        blank=True, help_text="GEDCOM date string", max_length=100
                    ),
                ),
                ("is_living", models.BooleanField(default=True)),
                (
                    "gedcom_data",
                    models.TextField(
                        blank=True, help_text="Raw GEDCOM for this record"
                    ),
                ),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True, related_name="individuals", to="genealogy.media"
                    ),
                ),
                (
                    "notes",
                    models.ManyToManyField(
                        blank=True, related_name="individuals", to="genealogy.note"
                    ),
                ),
                (
                    "birth_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="births",
                        to="genealogy.place",
                    ),
                ),
                (
                    "death_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deaths",
                        to="genealogy.place",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True, related_name="individuals", to="genealogy.source"
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individuals",
                        to="genealogy.tree",
                    ),
                ),
            ],
            options={
                "ordering": ["surname", "given_names"],
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "xref",
                    models.CharField(
                        help_text="GEDCOM cross-reference identifier (e.g. F1)",
                        max_length=50,
                    ),
                ),
                (
                    "marriage_date",
                    models.CharField(
                        blank=True, help_text="GEDCOM date string", max_length=100
                    ),
                ),
                (
                    "divorce_date",
                    models.CharField(
                        blank=True, help_text="GEDCOM date string", max_length=100
                    ),
                ),
                (
                    "gedcom_data",
                    models.TextField(
                        blank=True, help_text="Raw GEDCOM for this record"
                    ),
                ),
                (
                    "children",
                    models.ManyToManyField(
                        blank=True,
                        related_name="child_of_families",
                        to="genealogy.individual",
                    ),
                ),
                (
                    "husband",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="families_as_husband",
                        to="genealogy.individual",
                    ),
                ),
                (
                    "wife",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="families_as_wife",
                        to="genealogy.individual",
                    ),
                ),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True, related_name="families", to="genealogy.media"
                    ),
                ),
                (
                    "notes",
                    models.ManyToManyField(
                        blank=True, related_name="families", to="genealogy.note"
                    ),
                ),
                (
                    "marriage_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marriages",
                        to="genealogy.place",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True, related_name="families", to="genealogy.source"
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="families",
                        to="genealogy.tree",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "families",
                "ordering": ["xref"],
            },
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fact_type",
                    models.CharField(
                        choices=[
                            ("BIRT", "Birth"),
                            ("CHR", "Christening"),
                            ("DEAT", "Death"),
                            ("BURI", "Burial"),
                            ("CREM", "Cremation"),
                            ("ADOP", "Adoption"),
                            ("BAPM", "Baptism"),
                            ("BARM", "Bar Mitzvah"),
                            ("BASM", "Bat Mitzvah"),
                            ("CENS", "Census"),
                            ("CONF", "Confirmation"),
                            ("EMIG", "Emigration"),
                            ("FCOM", "First Communion"),
                            ("GRAD", "Graduation"),
                            ("IMMI", "Immigration"),
                            ("NATU", "Naturalization"),
                            ("ORDN", "Ordination"),
                            ("PROB", "Probate"),
                            ("RETI", "Retirement"),
                            ("WILL", "Will"),
                            ("EVEN", "Event"),
                            ("CAST", "Caste"),
                            ("DSCR", "Physical Description"),
                            ("EDUC", "Education"),
                            ("IDNO", "ID Number"),
                            ("NATI", "Nationality"),
                            ("NCHI", "Number of Children"),
                            ("NMR", "Number of Marriages"),
                            ("OCCU", "Occupation"),
                            ("PROP", "Property"),
                            ("RELI", "Religion"),
                            ("RESI", "Residence"),
                            ("SSN", "Social Security Number"),
                            ("TITL", "Title"),
                            ("ANUL", "Annulment"),
                            ("DIV", "Divorce"),
                            ("DIVF", "Divorce Filed"),
                            ("ENGA", "Engagement"),
                            ("MARB", "Marriage Bann"),
                            ("MARC", "Marriage Contract"),
                            ("MARL", "Marriage License"),
                            ("MARR", "Marriage"),
                            ("MARS", "Marriage Settlement"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Fact value (e.g. occupation name)",
                        max_length=512,
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        blank=True, help_text="GEDCOM date string", max_length=100
                    ),
                ),
                (
                    "gedcom_data",
                    models.TextField(
                        blank=True, help_text="Raw GEDCOM snippet for this fact"
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="genealogy.family",
                    ),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="genealogy.individual",
                    ),
                ),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True, related_name="facts", to="genealogy.media"
                    ),
                ),
                (
                    "notes",
                    models.ManyToManyField(
                        blank=True, related_name="facts", to="genealogy.note"
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facts",
                        to="genealogy.place",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True, related_name="facts", to="genealogy.source"
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="genealogy.tree",
                    ),
                ),
            ],
            options={
                "ordering": ["fact_type", "date"],
            },
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["tree", "name"], name="genealogy_p_tree_id_8dbb77_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="note",
            unique_together={("tree", "xref")},
        ),
        migrations.AlterUniqueTogether(
            name="media",
            unique_together={("tree", "xref")},
        ),
        migrations.AddIndex(
            model_name="individual",
            index=models.Index(
                fields=["tree", "surname"], name="genealogy_i_tree_id_329428_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="individual",
            index=models.Index(
                fields=["tree", "xref"], name="genealogy_i_tree_id_fc7fe5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="individual",
            unique_together={("tree", "xref")},
        ),
        migrations.AlterUniqueTogether(
            name="family",
            unique_together={("tree", "xref")},
        ),
        migrations.AddIndex(
            model_name="fact",
            index=models.Index(
                fields=["tree", "fact_type"], name="genealogy_f_tree_id_859a90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fact",
            index=models.Index(
                fields=["individual", "fact_type"],
                name="genealogy_f_individ_f218fd_idx",
            ),
        ),
    ]
